### ISSUE TITLE
can't upgrade to 0.17.1 from 0.16.0

### ISSUE THREAD

**Issue by yegor256** [dokku/sshcommand#119]
I can't upgrade to the latest version, it's:

```
$ sudo apt-get upgrade sshcommand
Reading package lists... Done
Building dependency tree
Reading state information... Done
sshcommand is already the newest version (0.16.0).
Calculating upgrade... Done
The following packages have been kept back:
  dokku
0 upgraded, 0 newly installed, 0 to remove and 1 not upgraded.
```

What do I do wrong? See also: https://github.com/dokku/dokku/issues/6204

**Comment by yegor256** [comment]
@josegonzalez can you please help?

**Comment by josegonzalez** [comment]
What version of Ubuntu are you running?

**Comment by yegor256** [comment]
@josegonzalez here:

```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.6 LTS
Release:	18.04
Codename:	bionic
```

**Comment by josegonzalez** [comment]
We don't support 18.04 anymore - neither does Ubuntu. The packages _might_ still work if you want to download them and manually install, but ymmv.

**Comment by IlyaSemenov** [comment]
dokku being stuck in "kept back" state prevents upgrading Ubuntu with `do-release-upgrade`. Does anyone have a recipe for performing the release upgrade without uninstalling dokku?

**Comment by josegonzalez** [comment]
You could download the deb package from the repo and install it on your server.

**Comment by IlyaSemenov** [comment]
Actually, uninstalling dokku - upgrading Ubuntu - reinstalling dokku mostly worked. I had to perform some maintenance (update and reinstall plugins, ps:rebuild stuck apps) but no data was lost.
