### ISSUE TITLE
no-user-rc breaks dropbear

### ISSUE THREAD

**Issue by Downchuck** [dokku/sshcommand#13]
The dropbear ssh daemon does not support the no-user-rc restriction.

**Comment by progrium** [comment]
I guess I'd take a PR with a global var set with whether or not its
dropbear and then leaving that out if it's set?

On Mon, Mar 30, 2015 at 12:43 PM, Charles Pritchard <
notifications@github.com> wrote:

> The dropbear ssh daemon does not support the no-user-rc restriction.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/progrium/sshcommand/issues/13>.
>



-- 
Jeff Lindsay
http://progrium.com

**Comment by Downchuck** [comment]
Could do: a flag like allow_rc, or something of that sort, with a note that
it's required for dropbear users.

I've sent a note over to the dropbear project as the flag is covered in man
allowed_keys.
