### ISSUE TITLE
Debian package should install command in /usr/bin

### ISSUE THREAD

**Issue by hansmi** [dokku/sshcommand#28]
The `dokku` package depends on `sshcommand` and uses an unqualified name:

```
# grep sshcommand /var/lib/dpkg/info/dokku.postinst
    sshcommand create dokku /usr/local/bin/dokku
        sshcommand acl-add dokku default < "$RET" || true
```

There are environments where PATH does not contain `/usr/local/bin` during package installation, e.g. in Puppet (PATH is `/bin:/sbin:/usr/bin:/usr/sbin`). Consequently the `dokku` package fails to install (`/var/lib/dpkg/info/dokku.postinst: line 17: sshcommand: command not found`). The underlying issue is the location used by the `sshcommand` package, however.

The package for Debian/Ubuntu distributions installs the `sshcommand` binary in `/usr/local/bin`. [According to the FHS](http://www.pathname.com/fhs/2.2/fhs-4.9.html) `/usr/local` is to for “use by the system administrator when installing software locally”.

**Comment by michaelshobbs** [comment]
@josegonzalez thoughts?

**Comment by josegonzalez** [comment]
Makes sense to me. Probably worth running all built packages through lintian again.

@hansmi I'm going to close this issue, can you re-open in the dokku repository, as that is where we do deb packaging for this.
