### ISSUE TITLE
Replace deluser with userdel in test scripts

### ISSUE THREAD

**Issue by callahad** [dokku/sshcommand#36]
Currently the `delete_user` helper [uses deluser](https://github.com/dokku/sshcommand/blob/cb34d558fdc3ec7e67b02e5803707d03b83a8781/tests/unit/test_helper.bash#L101), which is a Debian-specific wrapper around `userdel`.

For these purposes, `userdel --remove` should be a drop-in, portable replacement.

**Comment by josegonzalez** [comment]
Closing as there is a pull request open.
