### ISSUE TITLE
Avoid writing acl-add keys to a temporary file 

### ISSUE THREAD

**Issue by callahad** [dokku/sshcommand#37]
Right now, when passing a key to `acl-add` over stdin, [the key is written to a tempfile](https://github.com/dokku/sshcommand/blob/cb34d558fdc3ec7e67b02e5803707d03b83a8781/tests/unit/test_helper.bash#L101).

Since #34 landed, we never actually read from that file. So we could probably get rid of it altogether and just use pipes / shell variables...

**Comment by josegonzalez** [comment]
Hmmm was that the correct code link?

**Comment by callahad** [comment]
Yeah, that's definitely the wrong link :disappointed: I'll try to dig up the correct line of code and check if it's still relevant three years later :grin:

**Comment by callahad** [comment]
I think I was looking at:

https://github.com/dokku/sshcommand/blob/10272a8d176ddd665d597f58853c3ecfd5325749/sshcommand#L140-L142

and thinking "why do we even bother with synthesizing a `$KEY_FILE` there?"

**Comment by callahad** [comment]
If we could just read stdin into `$KEY` directly, then we could avoid the `mktemp` and the need to trap and try to clean up the `$KEY_FILE`
