### ISSUE TITLE
sshcommand create, group already exists

### ISSUE THREAD

**Issue by D1ceWard** [dokku/sshcommand#40]
Hello,
I'm an Arch Linux user.
`sshcommand create example  /bin/command` give me `groupadd: group 'example' already exists` and fail the command...

In sshcommand executable  :
```Shell
 case $l_platform in
    ...
    *)
      useradd -m -s /bin/bash "$l_user"
      groupadd "$l_user" # where the error occur
      usermod -L -aG "$l_user" "$l_user"
      ;;
  esac
```
From the man of `useradd`  on Arch
> By default, a group will also be created for the new user (see -g, -N, -U, and USERGROUPS_ENAB).

Is there any purpose of adding `groupadd "$l_user"` ?

I can make an PR, should i remove `groupadd "$l_user"` line ?
Or create an specific Arch case in fn-adduser() ?
```Shell
fn-adduser() {
  declare desc="Add a user to the system"
  local l_user l_platform

  l_user=$1
  l_platform="$(fn-print-os-id)"
  case $l_platform in
    alpine)
      adduser -D -g "" -s /bin/bash "$l_user"
      passwd -u "$l_user"
      ;;
    debian*|ubuntu|raspbian*)
      adduser --disabled-password --gecos "" "$l_user"
      ;;
    *)
      useradd -m -s /bin/bash "$l_user"
      groupadd "$l_user"
      usermod -L -aG "$l_user" "$l_user"
      ;;
  esac
}
```

**Comment by josegonzalez** [comment]
Closing as the pull request was merged :)
